/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricalRatePointDto } from './historicalRatePointDto';


export interface ApiResponseDtoListHistoricalRatePointDto { 
    success?: boolean;
    message?: string;
    data?: Array<HistoricalRatePointDto>;
    timestamp?: string;
}

