/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConversionResponseDto } from './conversionResponseDto';


export interface ApiResponseDtoConversionResponseDto { 
    success?: boolean;
    message?: string;
    data?: ConversionResponseDto;
    timestamp?: string;
}

