/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LatestRatesResponseDto } from './latestRatesResponseDto';


export interface ApiResponseDtoLatestRatesResponseDto { 
    success?: boolean;
    message?: string;
    data?: LatestRatesResponseDto;
    timestamp?: string;
}

