/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfficialRateResponseDto } from './officialRateResponseDto';


export interface ApiResponseDtoOfficialRateResponseDto { 
    success?: boolean;
    message?: string;
    data?: OfficialRateResponseDto;
    timestamp?: string;
}

