/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompareRatesResponseDto { 
    code?: string;
    fromDate?: string;
    toDate?: string;
    rateFrom?: number;
    rateTo?: number;
    changePercent?: string;
}

