/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConversionResponseDto { 
    from?: string;
    to?: string;
    amount?: number;
    rate?: number;
    convertedAmount?: number;
    date?: string;
}

