/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExchangeRateDto } from './exchangeRateDto';


export interface CurrencyResponseDto { 
    id?: number;
    nameFr?: string;
    nameAr?: string;
    unity?: number;
    code?: string;
    createdAt?: string;
    updatedAt?: string;
    publishedAt?: string;
    exchangeRates?: Array<ExchangeRateDto>;
}

