/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExchangeRateDto { 
    id?: number;
    day?: string;
    value?: string;
    createdAt?: string;
    updatedAt?: string;
    publishedAt?: string;
    endDate?: string;
}

