/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Item { 
    code?: string;
    name?: string;
    officialRate?: number;
    buyRate?: number;
    sellRate?: number;
    change24h?: string;
}

