/**
 * MauriExchange Currency API
 *
 * Contact: support@mauriexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Item } from './item';


export interface LatestRatesResponseDto { 
    date?: string;
    data?: Array<Item>;
}

