spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  security:
    user:
      name: ${ADMIN_USER}
      password: ${ADMIN_PASSWORD}

logging:
  level:
    com.mauriexchange: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

mauriexchange:
  exchange:
    cache:
      ttl-seconds: 300
    rate-limiter:
      requests-per-minute: 100
