spring:
  application:
    name: mauriexchange-backend
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mauriexchange}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:rootpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin123}
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Logging Configuration
logging:
  level:
    com.mauriexchange: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: Mauriexchange API
    description: Currency Exchange API for Mauritania - Aggregating exchange rates from Central Bank and national banks
    version: 1.0.0
    contact:
      name: Mauriexchange Team
      email: dev@mauriexchange.com
      url: https://mauriexchange.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
  servers:
    - url: http://localhost:8080/api/v1
      description: Local Development
    - url: https://mauriexchange-backend.fly.dev/api/v1
      description: Production

# Application Specific Configuration
mauriexchange:
  api:
    version: v1
    base-path: /api/v1
  exchange:
    supported-currencies:
      - MRU
      - USD
      - EUR
      - XOF
      - GBP
    cache:
      ttl-seconds: 300
    rate-limiter:
      requests-per-minute: 100
  security:
    cors:
      allowed-origins:
        - http://localhost:4200
        - https://mauriexchange.vercel.app
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
