spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mauriexchange_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: rootpass
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.mauriexchange: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

mauriexchange:
  exchange:
    cache:
      ttl-seconds: 60
    rate-limiter:
      requests-per-minute: 1000
